# Generated by Django 4.0.3 on 2022-06-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_completedconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedconversation',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversation.conversation', to_field='uuid'),
        ),
    ]
